<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>co.edu.usc.voltacali</groupId>
    <artifactId>parcial-voltacali</artifactId>
    <version>1.0</version>
    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>
</project>
